[2010-11-08 08:56:47,226] [ERROR] from read in snc at snc.py:116 :
failed to read [len=4]:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-11-08 08:56:47,242] [WARNING] from send in sync_dir at sync_dir.py:199 :
network error while synchronizing directory

[2010-11-08 08:58:04,398] [ERROR] from read in snc at snc.py:116 :
failed to read [len=4]:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-11-08 08:58:04,398] [WARNING] from send in sync_dir at sync_dir.py:199 :
network error while synchronizing directory

[2010-11-08 08:59:08,957] [ERROR] from send in sync_dir at sync_dir.py:207 :
failed to synchronize directory: OSError(9, 'Bad file descriptor')

[2010-11-08 09:07:50,096] [ERROR] from read in snc at snc.py:116 :
failed to read [len=4]:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-11-08 09:07:50,096] [WARNING] from send in sync_dir at sync_dir.py:201 :
network error while synchronizing directory

[2010-11-08 09:16:11,614] [ERROR] from read in snc at snc.py:116 :
failed to read [len=4]:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-11-08 09:16:11,614] [WARNING] from send in sync_dir at sync_dir.py:201 :
network error while synchronizing directory

[2010-11-08 09:17:16,863] [ERROR] from read in snc at snc.py:116 :
failed to read [len=4]:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-11-08 09:17:16,863] [WARNING] from send in sync_dir at sync_dir.py:201 :
network error while synchronizing directory

[2010-11-08 09:18:36,687] [ERROR] from read in snc at snc.py:116 :
failed to read [len=4]:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-11-08 09:18:36,687] [WARNING] from send in sync_dir at sync_dir.py:201 :
network error while synchronizing directory

[2010-11-08 09:19:09,563] [ERROR] from read in snc at snc.py:116 :
failed to read [len=4]:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-11-08 09:19:09,564] [WARNING] from send in sync_dir at sync_dir.py:201 :
network error while synchronizing directory

