[2010-09-30 11:01:58,502] [INFO] from run_server in main at main.py:69 :
orzoj-server started, listening on 9351

[2010-09-30 11:02:00,120] [INFO] from run_server in main at main.py:82 :
connected by '127.0.0.1:35626'

[2010-09-30 11:02:00,612] [INFO] from run in work at work.py:397 :
[judge 'orzoj-judge-default'] successfully connected

[2010-09-30 11:02:03,714] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #19

[2010-09-30 11:02:03,728] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:07:13,627] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #20

[2010-09-30 11:07:13,683] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:07:31,121] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #21

[2010-09-30 11:07:31,156] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:09:22,870] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #22

[2010-09-30 11:09:22,924] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:09:23,509] [INFO] from _solve_task in work at work.py:257 :
[judge 'orzoj-judge-default'] file transfer speed: 0.0362253319979 kb/s

[2010-09-30 11:09:23,629] [INFO] from _solve_task in work at work.py:257 :
[judge 'orzoj-judge-default'] file transfer speed: 4.05283569589 kb/s

[2010-09-30 11:09:23,749] [INFO] from _solve_task in work at work.py:257 :
[judge 'orzoj-judge-default'] file transfer speed: 0.0732705798497 kb/s

[2010-09-30 11:09:48,634] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #23

[2010-09-30 11:09:48,667] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:09:50,270] [WARNING] from _solve_task in work at work.py:304 :
[judge 'orzoj-judge-default'] message check error

[2010-09-30 11:09:50,271] [INFO] from _clean in work at work.py:157 :
[judge 'orzoj-judge-default'] disconnected

[2010-09-30 11:15:17,288] [INFO] from run_server in main at main.py:82 :
connected by '127.0.0.1:60792'

[2010-09-30 11:15:17,764] [INFO] from run in work at work.py:397 :
[judge 'orzoj-judge-default'] successfully connected

[2010-09-30 11:15:17,765] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:15:19,389] [DEBUG] from _read in web at web.py:262 :
raw data from server: '\nNotice: unserialize(): Error at offset 0 of 19 bytes in /home/jiakai/programming/orzoj/website/msg.php on line 419\n{"status":0,"data":"null","checksum":"bc2e9bd022b62dd8583c0622c9e004bbb67fa01c"}'

[2010-09-30 11:15:19,389] [ERROR] from _read in web at web.py:264 :
website communication error [left retries: 4]: ValueError('No JSON object could be decoded',)

[2010-09-30 11:15:19,401] [WARNING] from _read in web at web.py:241 :
website requests relogin

[2010-09-30 11:15:20,788] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #24

[2010-09-30 11:15:20,839] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:17:22,336] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #25

[2010-09-30 11:17:22,342] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:18:02,567] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #26

[2010-09-30 11:18:02,631] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:18:03,216] [INFO] from _solve_task in work at work.py:257 :
[judge 'orzoj-judge-default'] file transfer speed: 0.0716296255547 kb/s

[2010-09-30 11:20:41,387] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #27

[2010-09-30 11:20:41,439] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'apb'

[2010-09-30 11:20:42,023] [INFO] from _solve_task in work at work.py:257 :
[judge 'orzoj-judge-default'] file transfer speed: 17.1245787111 kb/s

[2010-09-30 11:20:45,114] [WARNING] from _solve_task in work at work.py:304 :
[judge 'orzoj-judge-default'] message check error

[2010-09-30 11:20:45,135] [INFO] from _clean in work at work.py:157 :
[judge 'orzoj-judge-default'] disconnected

[2010-09-30 11:21:31,079] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-09-30 11:21:31,079] [ERROR] from accept in snc at snc.py:78 :
socket error: error(4, 'Interrupted system call')

[2010-09-30 11:21:31,079] [DEBUG] from run_server in main at main.py:88 :
waiting for threads, current active count: 2

[2010-09-30 11:21:31,080] [DEBUG] from run_server in main at main.py:90 :
active thread: 'MainThread'

[2010-09-30 11:21:31,080] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work._thread_fetch_task'

